<?php

function match_dna($dna) {
    $dna_array = str_split($dna);
    $match_array = array();
    foreach ($dna_array as $letter) {
        $match_array[] = get_pair($letter);
    }
    return implode($match_array);
}

function get_pair($dna) {
    if ($dna === 'A') {
        return 'T';
    } elseif ($dna === 'T') {
        return 'A';
    } elseif ($dna === 'C') {
        return 'G';
    } elseif ($dna === 'G') {
        return 'C';
    } else {
        return NULL;
    }
}
